# Generated by Django 4.1.2 on 2023-04-03 05:25

from django.db import migrations, models


def forward_user_updates(apps, schema):
    User = apps.get_model('user', 'User')
    users = User.objects.all()
    for user in users:
        if not user.username:
            user.username = user.email
            user.save()
    pass


def reverse_user_updates(apps, schema):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_resets',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(code=forward_user_updates, reverse_code=reverse_user_updates),
    ]
