# Generated by Django 4.1.2 on 2023-04-14 06:38

from django.db import migrations, models
import django.db.models.deletion


def forward_address_updates(apps, schema):
    Address = apps.get_model('user', 'Address')
    addresses = Address.objects.all()
    for address in addresses:
        if not isinstance(address.state, int):
            address.state = None
            address.save()
    pass


def reverse_address_updates(apps, schema):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_state'),
    ]

    operations = [
        migrations.RunPython(code=forward_address_updates, reverse_code=reverse_address_updates),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.state'),
        ),
    ]
