# Generated by Django 4.1.2 on 2023-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('1', 'Home'), ('0', 'Office')], max_length=1),
        ),
    ]
