# Generated by Django 4.1.2 on 2023-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_id',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_code',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
