# Generated by Django 4.1.2 on 2023-03-20 13:16

from django.db import migrations, models
import django.db.models.deletion


def forward_function(apps, schema):
    category = apps.get_model('catalogue', 'Category')
    category.objects.filter(parent_category_id=0).update(parent_category_id=None)
    pass


def reverse_function(apps, schema):
    pass


def final_forward_function(apps, schema):
    category = apps.get_model('catalogue', 'Category')
    category.objects.filter(is_domestic=0, is_corporate=0).update(domestic_corporate=0)
    category.objects.filter(is_domestic=1).update(domestic_corporate=1)
    category.objects.filter(is_corporate=1).update(domestic_corporate=2)
    pass


def final_reverse_function(apps, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(code=forward_function, reverse_code=reverse_function),
        migrations.AddField(
            model_name='category',
            name='domestic_corporate',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Domestic'), (2, 'Corporate')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='catalogue.category'),
        ),
        migrations.RunPython(code=final_forward_function, reverse_code=final_reverse_function)
    ]
