# Generated by Django 4.1.2 on 2023-03-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_category_domestic_corporate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_corporate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_domestic',
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to='catalogue.medialibrary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brochure_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_pdf', to='catalogue.medialibrary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_image', to='catalogue.medialibrary'),
        ),
    ]
