# Generated by Django 4.1.2 on 2023-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_page_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='file_path',
            field=models.FileField(max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='thumb_file_path',
            field=models.FileField(max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='big_image_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb_image_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
