# Generated by Django 4.1.2 on 2023-03-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_medialibrary_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.medialibrary'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.medialibrary'),
        ),
    ]
