# Generated by Django 4.1.2 on 2023-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_cart_warranty_parent_and_more'),
        ('catalogue', '0008_alter_productvariant_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warranty',
        ),
    ]
