# Generated by Django 4.1.2 on 2023-03-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('catalogue', '0010_productmodel_producttype_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='installation_address',
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_address1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_address2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_district', to='user.district'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_landmark',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_pincode', to='user.citypincode'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='billing_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_state', to='user.state'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_address1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_address2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_district', to='user.district'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_landmark',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_pincode', to='user.citypincode'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='installation_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_state', to='user.state'),
        ),
    ]
