# Generated by Django 4.1.2 on 2023-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_alter_productreview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
