# Generated by Django 3.2.18 on 2023-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_productreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='mail',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='phone',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
