# Generated by Django 4.1.1 on 2023-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrderReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cancel_order_reasons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('retail_price', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_purchase_value', models.FloatField()),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('maximum_discount_value', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('offer_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=10)),
                ('validity_start_date', models.DateField()),
                ('validity_end_date', models.DateField()),
                ('applicable_for_full_order', models.IntegerField()),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('min_purchase_amount', models.FloatField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('browser_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=520, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferComboFreeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('fixed_price', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_combo_free_products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferComboProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_combo_products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('how_many_to_buy', models.IntegerField()),
                ('how_many_to_get_free', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferPriceProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_price_products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=17)),
                ('transaction_id', models.CharField(max_length=150)),
                ('coupon_discount', models.FloatField(blank=True, null=True)),
                ('order_reference_number', models.CharField(max_length=150)),
                ('total_mrp', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('total_sale_price', models.FloatField()),
                ('total_final_price', models.FloatField()),
                ('payment_method', models.CharField(max_length=250)),
                ('payment_status', models.IntegerField()),
                ('payment_receive_status', models.IntegerField()),
                ('delivery_address_id', models.IntegerField()),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('is_cancelled', models.IntegerField()),
                ('cancelled_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mrp', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('customer_instructions', models.TextField(blank=True, null=True)),
                ('warranty_parent', models.IntegerField(blank=True, null=True)),
                ('is_returned', models.IntegerField()),
                ('returned_reason', models.TextField(blank=True, null=True)),
                ('is_cancelled', models.IntegerField()),
                ('cancelled_reason', models.TextField(blank=True, null=True)),
                ('refund_request_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLabelsMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_order', models.IntegerField()),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_status_labels_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_tracking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': True,
            },
        ),
    ]
