# Generated by Django 4.1.2 on 2023-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='warranty_parent',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='waranty',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='warranty_parent',
        ),
    ]
