# Generated by Django 4.1.2 on 2023-04-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_address_country_id_alter_address_created_at_and_more'),
        ('catalogue', '0012_alter_warranty_contact_person'),
        ('order', '0005_alter_cart_created_at_alter_cart_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online')], default='online', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_receive_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_started', 'Payment Started'), ('payment_completed', 'Payment Completed'), ('cod', 'Cash On Delivery')], default='payment_started', max_length=17),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderstatuslabelsmaster'),
        ),
    ]
