# Generated by Django 4.1.2 on 2023-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_cancelorderreason_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
