# Generated by Django 4.1.2 on 2023-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderdetail_other_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
