# Generated by Django 4.1.2 on 2023-04-19 05:21

from django.db import migrations, models


def forward_function(apps, schema):
    Order = apps.get_model('order', 'Order')
    Order.objects.all().update(placed=True)
    pass


def reverse_function(apps, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_order_other_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(code=forward_function, reverse_code=reverse_function),
    ]
